CC=g++
CFLAGS=-std=c++11

out : main.cpp ConcreteImplementorA.h ConcreteImplementorB.h RefinedAbstraction.h Abstraction.h
	$(CC) $(CFLAGS) -o out main.cpp ConcreteImplementorA.h ConcreteImplementorB.h RefinedAbstraction.h Abstraction.h


